### PR TITLE
Remove the bare except statement from the Cursor's fetchone method.

### PR DESCRIPTION
**Pull request by stankudrow**
Resolves the issue #117 .

### CODE REVIEW

**Comment by stankudrow** [comment]
@llchan, could you possibly review this PR and approve if you like it?

@long2ice , hello, it is up to you whether to merge this PR before the new asynch release or after.

Thank you all in advance.

**Comment by stankudrow** [comment]
@long2ice , @llchan, any suggestions?

**Comment by llchan** [comment]
LGTM.  It may be better to tighten in the future but this at least addresses my concerns about signals getting discarded.  I don't think I can approve/merge the PR though so we still need to wait for a maintainer.

**Comment by stankudrow** [comment]
> LGTM. It may be better to tighten in the future but this at least addresses my concerns about signals getting discarded. I don't think I can approve/merge the PR though so we still need to wait for a maintainer.

You have already expressed your support, thank you. Could you share your ideas on tiding and suggestions about future improvements?

**Comment by stankudrow** [comment]
@llchan , done in the #119 , you can close the issue #118 .

**Pull request closed without merging**
