### PR TITLE
Fix BufferReader.reader_bytes

### PR DESCRIPTION
**Pull request by ikrivosheev**
Fix https://github.com/long2ice/asynch/issues/10

### CODE REVIEW

**Comment by long2ice** [comment]
Could you add tests to execute sql to show it's correct? There is a ClickHouse instance when CI

**Comment by long2ice** [comment]
In fact I don't know why #10 happened, insert is tested in tests before

**Comment by ikrivosheev** [comment]
@long2ice I see some sql tests in tests/test_cursor.py. Which tests do you want?

**Comment by ikrivosheev** [comment]
> In fact I don't know why #10 happened, insert is tested in tests before

Simple test to reproduce:

```python
stream_data = b"1234"
stream_reader = StreamReader()
stream_reader.feed_data(stream_data)
reader = BufferedReader(stream_reader, 1)

await reader.read_bytes(4)
await reader.read_varint()
```

**Comment by long2ice** [comment]
Test the error one you show there

**Comment by ikrivosheev** [comment]
@long2ice Done

**Comment by long2ice** [comment]
Great! Thanks!

**Pull request merged**
